import "./globals.css";
import { Roboto_Mono } from "next/font/google";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import ScrollProgress from "@/components/ScrollProgress";
import ToTop from "@/components/ToTop";

const inter = Roboto_Mono({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}
            style={{backgroundImage: 'url("https://api.maho.cc/random-img/mobile.php")',
                backgroundSize: 'cover',
                backgroundAttachment: 'fixed'}}>
      <div className={"min-h-screen flex flex-col"}>
          <ScrollProgress />
          <ToTop />
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  )
}
