import "./globals.css";
import { Roboto_Mono } from "next/font/google";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { ScrollProgressProvider } from "@/components/ScrollProgress";
import ToTop from "@/components/ToTop";
import { ThemeProvider } from "@/components/ThemeProvider"
import { TailwindIndicator } from "@/components/TailwindIndicator";
import { cn } from "@/lib/utils";
import BackgroundImage from "@/components/background-image/BackgroundImage";

const inter = Roboto_Mono({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

type RootLayoutProps = {
    children: React.ReactNode
}

export default function RootLayout({ children }: RootLayoutProps) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={cn(inter.className, "static")}>
                <BackgroundImage/>
                <div className={"absolute top-0 w-full"}>
                    <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
                        <ScrollProgressProvider>
                            <div className={"flex flex-col"}>
                                <Header />
                                {children}
                                <Footer />
                                <TailwindIndicator />
                                <ToTop />
                            </div>
                        </ScrollProgressProvider>
                    </ThemeProvider>
                </div>
            </body>
        </html>
    )
}
