import "./globals.css";
import { Open_Sans } from "next/font/google";
import { cn } from "@/lib/utils";
import { Providers } from "@/providers";

const font = Open_Sans({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

type RootLayoutProps = {
    children: React.ReactNode
}

export default function RootLayout({ children }: RootLayoutProps) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={cn(font.className, "static")}>
                <Providers>
                    {children}
                </Providers>
            </body>
        </html>
    )
}
